// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iejvpcvpngnzpbtqnnly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllanZwY3ZwbmduenBidHFubmx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODUzMDUsImV4cCI6MjA2NjI2MTMwNX0._5mMb7R_apJVNC1ObJcGnMREBDy0yEcRzFVUejJEPdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);